# Customer Behaviour Analysis

#### 1. Import required libreries and load dataset

In [1]:
import pandas as pd 
import numpy as np

In [2]:

df= pd.read_csv("customer_shopping_behavior.csv")

#### 2. dataset checks and cleaning
1. Null valuse
2. Duplicate valuse

In [3]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [5]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [6]:
first_time_customers = df[df['previous_purchases'] == 0]['customer_id']

# To see the results
print(first_time_customers)

Series([], Name: customer_id, dtype: int64)

In [7]:
# df.describe() this gives the summary of "numerical columns" only 

df.describe(include='all') 
# this will give the summary of num and cat colums

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [8]:
#check missing values 
df.isnull().sum()

customer_id                0
age                        0
gender                     0
item_purchased             0
category                   0
purchase_amount            0
location                   0
size                       0
color                      0
season                     0
review_rating             37
subscription_status        0
shipping_type              0
discount_applied           0
promo_code_used            0
previous_purchases         0
payment_method             0
frequency_of_purchases     0
dtype: int64

**There are 37 null values in the "Review Rating"**<br>
we have to replace the data with Mean/Meadian---> which to choose ?

<u>**1. Mean?**</u><br> 
❌Mean can get affected by outliers that would skew the distrbution of the data

<u>**3. median**</u><br>
  ❌overall median (not best practice)
  because ratings can vary depending on the category(bias in dataset)<br>
  <u>✅impute the  median values with the median values of the category </u>

In [9]:
df['review_rating'] = df.groupby('category')['review_rating'].transform(
    lambda x: x.fillna(x.median())
)

**cleaning the dataset headers**

#### 3. Feature Engineering data exploration & analysis

In [10]:
# *Create a column age_group*

#pd.qcut is a pandas function used to divide a numeric series into equal-sized bins (quantiles).
# Can you use qcut with custom edges(edge value separating groups)? 
# NO ,If you want specific edges, you should use pd.cut.# Define manual bin edgesbins = [20, 30, 40, 55, 70]
# qcut is only for when you want equal-sized bins by count.

labels=['Young Adult', 'Adults','Middle-aged','senior']
df['age_group']=pd.qcut(df['age'],q=4,labels =labels)

In [11]:
df[['age','age_group']].head()
#Selects only the age and age_group

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged

In [12]:
# create column purchase_frequency-days 
# (how often a customer purchases) but in cat->> weekly,monthly ,yearly

# convert to numerical ,number of days between purchases

frequency_mapping={'Fortnightly':14,
                   'Weekly':7,
                   'Monthly':30,
                   'Quarterly':90,
                   'Bi-Weekly':14,
                   'Annually':365,
                   'Every 3 Months': 90
                  }

df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

# map() loops internally through each element in the Series:
# Check if the element exists in the dictionary keys.
# If yes → replace it with the corresponding value from the dictionary.
# If no → replace it with NaN

In [13]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

**Redundent colums check**

In [14]:
df[['discount_applied', 'promo_code_used']].head()
# do we actually need both the columns ,  is on of the column  redundent

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes

In [15]:
(df['discount_applied'] == df['promo_code_used']).all()

# all() Checks if all values in the boolean Series are True.

np.True_

In [16]:
df=df.drop('promo_code_used',axis=1)

In [17]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

#### 4.connecting to postgres

In [18]:
pip install ipython-sql sqlalchemy psycopg2-binary

Requirement already satisfied: ipython-sql in c:\users\user\anaconda3\lib\site-packages (0.5.0)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: sqlalchemy in c:\users\user\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: psycopg2-binary in c:\users\user\anaconda3\lib\site-packages (2.9.11)
Requirement already satisfied: prettytable in c:\users\user\anaconda3\lib\site-packages (from ipython-sql) (3.17.0)
Requirement already satisfied: ipython in c:\users\user\anaconda3\lib\site-packages (from ipython-sql) (8.30.0)
Requirement already satisfied: sqlparse in c:\users\user\anaconda3\lib\site-packages (from ipython-sql) (0.5.4)
Requirement already satisfied: six in c:\users\user\anaconda3\lib\site-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in c:\users\user\anaconda3\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\user\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\user\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: decorator in c:\users\user\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\user\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: matplotlib-inline in c:\users\user\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\user\anaconda3\lib\site-packages (from ipython->ipython-sql) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\user\anaconda3\lib\site-packages (from ipython->ipython-sql) (2.19.1)
Requirement already satisfied: stack-data in c:\users\user\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\user\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: colorama in c:\users\user\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: wcwidth in c:\users\user\anaconda3\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython->ipython-sql) (0.2.5)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\user\anaconda3\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.4)
Requirement already satisfied: executing in c:\users\user\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: asttokens in c:\users\user\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (3.0.0)
Requirement already satisfied: pure-eval in c:\users\user\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.2.2)

In [19]:
from sqlalchemy import create_engine

username = 'postgres'
password = '12345678' 
host = "localhost"
port = '5432'
database = 'customer_behaviour'

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name = "customer"
df.to_sql(table_name, engine, if_exists='replace', index=False)

print(f"Data successfully loaded into table '{table_name}' in '{database}'.")

Data successfully loaded into table 'customer' in 'customer_behaviour'.

In [20]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365